name: quest_health
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  table_calendar: ^3.0.6
  google_fonts: ^3.0.1
  snippet_coder_utils: ^1.0.12
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logobesar.png"

flutter: 
  uses-material-design: true

  assets: 
    - assets/images/

